### ISSUE TITLE
How to modify orchest base images?

### ISSUE THREAD

**Issue by alexsanderp** [orchest/orchest#1199]
How to modify orchest base images? I tried to pass a custom image to EKS using kubectl apply, but it keeps going up using the default image.

```
apiVersion: orchest.io/v1alpha1
kind: OrchestCluster
metadata:
  name: cluster-1
  namespace: orchest
spec:
  singleNode: true
  orchest:
    orchestWebServer:
      image: alexsanderdadosfera/orchest-webserver:latest
```
