### ISSUE TITLE
Using orchest-controller to install orchest, orchest_node-agent is not installed.

### ISSUE THREAD

**Issue by im-jinxinwang** [orchest/orchest#1537]
**Describe the bug**
Using orchest-controller to install orchest, orchest_node-agent is not installed.
```text
# kubectl get ds -n orchest 
No resources found in orchest namespace.
```
I am using the following deployment file.
```yaml
apiVersion: orchest.io/v1alpha1
kind: OrchestCluster
metadata:
  name: cluster-1
  namespace: orchest
spec:
  singleNode: true
```

**Expected behavior**

Do I need to configure the orchest-node-agent service separately for installation?

**Screenshots**
![image](https://github.com/orchest/orchest/assets/39941928/e84b3168-d924-44cf-8e30-45b2ce1e1c3d)

**Environment**

- OS (e.g. macOS):  centos 7.9
- Browser (e.g. Chrome):  Chrome
- Orchest's version (in the settings page):
